name: Playwright Tests
on:
  push:
    branches: [main, master, staging]
  pull_request:
    branches: [main, master, staging]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ^8.15.7
      - uses: actions/setup-node@v4
        with:
          node-version: 20.5.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright with deps
        run: npx playwright install --with-deps

      # - name: Run tests
      #   run: pnpm test:e2e
      #   env:
      #     PLAYWRIGHT_TEST_BASE_URL: https://staging-app.impulsecrm.io

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
